import './globals.css'
import Header from './components/Header'
import {Poppins} from "next/font/google" //importing font from google

const poppins = Poppins({ //using the imported fonts
  weight:"400",
  subsets:['latin'],
  display:'swap'
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
  <html lang="en" className={poppins.className}>
      <body>
        <Header/>
        {children}</body>
    </html>
  )
}
